07_08_django_hasker/homework/hasker/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hasker_accounts.urls')),
    path('', include('hasker_qa.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = \
        [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + \
        urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07_08_django_hasker/homework/hasker/hasker_qa/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ask/', views.AskView.as_view(), name='ask'),
    path('question/<int:pk>/', views.QuestionView.as_view(), name='question'),
    path('question/<int:pk>/vote/', views.QuestionVoteView.as_view(), name='question_vote'),
    path('answer/', views.AnswerView.as_view(), name='answer'),
    path('answer/<int:pk>/vote/', views.AnswerVoteView.as_view(), name='answer_vote'),
    path('answer/<int:pk>/mark/', views.AnswerMarkView.as_view(), name='answer_mark'),
]

07_08_django_hasker/homework/hasker/hasker_qa/models.py
from django.core.mail import send_mail
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse

from hasker_accounts.models import User


class Tag(models.Model):
    name = models.CharField(
        unique=True,
        max_length=255,
        help_text='Tag name.',
    )


class Question(models.Model):
    title = models.CharField(
        max_length=255,
        help_text='Describe your question title.',
    )
    text = models.TextField(
        help_text='Describe your question body.',
    )
    tags = models.ManyToManyField(
        Tag,
        blank=True,
        help_text='Choice tags for your question.',
    )
    creation_date = models.DateTimeField(
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        help_text='Choice tags for your question.',
    )

    def get_absolute_url(self):
        return self.get_url(self.id)

    @staticmethod
    def get_url(id_):
        return reverse("question", kwargs={'pk': str(id_)})

    def email_author(self):
        subject = f"Check new answer on Hasker question: {self.title}"
        message = f"""
            There is new answer for the question "{self.title}". You can view it by url: {self.get_absolute_url()}
            """
        send_mail(subject, message, None, [self.author.email])


class Answer(models.Model):
    text = models.TextField(
        help_text='Provide answer for a question.',
    )
    creation_date = models.DateTimeField(
        auto_now_add=True,
    )
    correct_answer = models.NullBooleanField(
        default=False,
        help_text='Choose correct answer.',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='answers',
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name='answers',
    )
    unique_together = ('correct_answer', 'question')

    def get_absolute_url(self):
        return Question.get_url(self.question.id)


class AbstractVoteUser(models.Model):
    class Meta:
        abstract = True

    SIGN_CHOICES = [
        (1, 'Plus'),
        (-1, 'Minus'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sign = models.SmallIntegerField(choices=SIGN_CHOICES)


class AnswerVoteUser(AbstractVoteUser):
    class Meta:
        constraints = [
            UniqueConstraint(fields=['entity', 'user'], name='unique_answer_user')
        ]

    entity = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='votes')


class QuestionVoteUser(AbstractVoteUser):
    class Meta:
        constraints = [
            UniqueConstraint(fields=['entity', 'user'], name='unique_question_user')
        ]

    entity = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='votes')

07_08_django_hasker/homework/hasker/hasker_qa/forms.py
from django import forms

from hasker_qa.models import Question, Answer, AbstractVoteUser


class AskForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'text')

    tags = forms.CharField(help_text='Enter tags separated by space')

    def clean_tags(self):
        tags_list = self.cleaned_data['tags'].split(' ')
        if len(tags_list) > 3:
            raise forms.ValidationError("Tags more than 3!")

        return tags_list


class QuestionGetParamsForm(forms.Form):
    ORDERING_CHOICES = (
        ('votes_sum', ''),
    )
    ordering = forms.ChoiceField(choices=ORDERING_CHOICES, required=False)
    q = forms.CharField()


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text', 'question')

    question = forms.HiddenInput()


class VoteForm(forms.Form):
    sign = forms.ChoiceField(choices=AbstractVoteUser.SIGN_CHOICES, required=True)

    def clean_sign(self):
        return int(self.cleaned_data['sign'])

07_08_django_hasker/homework/hasker/hasker_qa/views.py
import re

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F, Q
from django.db.models.functions import Coalesce
from django.http import HttpRequest, QueryDict
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic.detail import BaseDetailView

from hasker_accounts.models import User
from hasker_qa.forms import AskForm, QuestionGetParamsForm, AnswerForm, VoteForm
from hasker_qa.models import Question, Answer, Tag

question_query_set = Question.objects. \
    annotate(votes_sum=Coalesce(Sum(F('votes__sign')), 0)). \
    select_related('author')


def common_context(context: dict, form_url: str = ''):
    context.update({
        'trending_questions': IndexView.queryset.order_by('-votes_sum'),
    }
    )
    if form_url:
        context.update({
            'form_url': reverse(form_url),
        }
        )


class IndexView(ListView):
    model = Question
    ordering = '-creation_date'
    template_name = 'hasker_qa/index.html'
    queryset = question_query_set
    context_object_name = 'questions'
    paginate_by = 20

    tag_regex = re.compile(r"tag:(?P<name>\w+?)$")

    def get_text_search(self, query):
        """Perfom a text search"""
        self.q_text = ''
        if self.form.is_valid():
            q_text = self.form.cleaned_data['q']
            self.q_text = q_text
            search = self.tag_regex.search(q_text)
            if search:
                tag_name = search.group('name')
                return query.filter(tags__name=tag_name)
            query = query.filter(Q(title__icontains=q_text) | Q(text__icontains=q_text))
        return query

    def get_queryset(self):
        self.form = form = QuestionGetParamsForm(self.request.GET)
        query = super().get_queryset()
        return self.get_text_search(query)

    def get_ordering(self):
        form = self.form
        if form.is_valid() and form.cleaned_data['ordering']:
            return '-votes_sum'
        return self.ordering

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        # Prepare get data for build with pagination
        qdict = QueryDict('', mutable=True)
        qdict.update(self.form.cleaned_data)
        self.request.GET = qdict
        context.update({
            'q_text': self.q_text,
        })
        return context


class AskView(LoginRequiredMixin, CreateView):
    template_name = 'hasker_qa/ask.html'
    form_class = AskForm

    def set_tags(self, tags_list):
        """Set tags for a question"""
        for tag_name in tags_list:
            tag, status = Tag.objects.get_or_create(name=tag_name)
            self.object.tags.add(tag)

    def form_valid(self, form):
        obj: Question = form.instance
        obj.author = self.request.user
        response = super().form_valid(form)

        self.set_tags(form.cleaned_data['tags'])
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        common_context(context, 'ask')
        return context

    def get_success_url(self):
        return self.object.get_absolute_url()


class QuestionView(DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'hasker_qa/question.html'
    queryset = question_query_set

    def set_vote_status(self, obj):
        sign = None
        sign_obj = obj.votes.filter(user=self.request.user.id).first()
        if sign_obj:
            sign = sign_obj.sign
        setattr(obj, 'vote_status', sign)

    def get_context_data(self, **kwargs):
        answers_list = []
        context = super().get_context_data(**kwargs)
        obj: Question = self.object
        self.set_vote_status(obj)

        answers = obj.answers.select_related('author'). \
            annotate(votes_sum=Coalesce(Sum(F('votes__sign')), 0)). \
            order_by('-votes_sum', '-creation_date')
        for answer in answers:
            # status for answer votes
            self.set_vote_status(answer)
            answers_list.append(answer)

        context.update({
            'answers': answers_list
        })
        common_context(context)
        return context


class AnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    http_method_names = ['post']

    def form_valid(self, form):
        obj: Answer = form.instance
        obj.author = self.request.user
        result: Answer = super().form_valid(form)
        if not settings.DEBUG:
            obj.question.email_author()
        return result


class ChangeAbstractView(LoginRequiredMixin, BaseDetailView):
    http_method_names = ['post']


class AnswerMarkView(ChangeAbstractView):
    """Mark right answer"""
    model = Answer

    def post(self, request, *args, **kwargs):
        answer: Answer = self.get_object()
        if answer.question.author == request.user:
            current_correct_answer: Answer = answer.question.answers.filter(correct_answer=True).first()
            if current_correct_answer:
                current_correct_answer.correct_answer = None
                current_correct_answer.save()
            # Check correct answer only if it different from current
            if current_correct_answer != answer:
                answer.correct_answer = True
                answer.save()
        return redirect(answer.get_absolute_url())


class VoteAbstractView(ChangeAbstractView):
    @staticmethod
    def change_vote(request: HttpRequest, obj, author):
        """Set vote if old not exist or change it or delete it."""
        current_user: User = request.user
        form = VoteForm(request.POST)
        if form.is_valid() and author != current_user:
            sign = form.cleaned_data['sign']
            existed_vote = obj.votes.filter(user=current_user).first()
            if existed_vote:
                existed_vote.delete()
            if existed_vote is None or existed_vote.sign != sign:
                obj.votes.model.objects.create(user=current_user, entity=obj, sign=sign)
        return redirect(obj.get_absolute_url())


class AnswerVoteView(VoteAbstractView):
    """Vote for answer"""
    model = Answer

    def post(self, request, *args, **kwargs):
        obj: Answer = self.get_object()
        question_author = obj.question.author
        return self.change_vote(request, obj, question_author)


class QuestionVoteView(VoteAbstractView):
    """Vote for Question"""
    model = Question

    def post(self, request, *args, **kwargs):
        obj: Question = self.get_object()
        question_author = obj.author
        return self.change_vote(request, obj, question_author)

07_08_django_hasker/homework/hasker/hasker_qa/templates/hasker_qa/index.html
{% extends 'base.html' %}

{% block content %}

    {% if questions %}
        {% for question in questions %}
            {% include "hasker_qa/question_info.html" %}
            Answers: {{ question.answers.count }}

            {% include "hasker_qa/question_tags.html" %}

            <hr class="my-4">
        {% endfor %}

        {% include 'pagination.html' %}
    {% else %}
        <h1>There are no questions find!</h1>
    {% endif %}

{% endblock %}

07_08_django_hasker/homework/hasker/hasker_qa/templates/hasker_qa/question.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        {% include "hasker_qa/question_info.html" %}
        <!-- Vote -->

        {% if user.is_authenticated and user != question.author %}
            <form method="post" action={% url 'question_vote' question.id %}>
                {% csrf_token %}
                <input type="hidden" name="sign" value="-1">
                {% if question.vote_status == -1 %}
                    <input class="button" type="submit" value="already -1" aria-pressed="true"/>
                {% else %}
                    <input class="button" type="submit" value="-1"/>
                {% endif %}
            </form>
            <form method="post" action={% url 'question_vote' question.id %}>
                {% csrf_token %}
                <input type="hidden" name="sign" value="1">
                {% if question.vote_status == 1 %}
                    <input class="button" type="submit" value="already +1" aria-pressed="true"/>
                {% else %}
                    <input class="button" type="submit" value="+1"/>
                {% endif %}
            </form>

        {% endif %}

        {% include "hasker_qa/question_tags.html" %}

    </div>
    <div>
        {% for answer in answers %}
            <div>
                <p>{{ answer.text }}</p>
                <div class="extra">
                    <p>
                        {% if answer.author.avatar %}
                            <img src="{{ media_prefix }}{{ answer.author.avatar }}" height="30" width="30"
                                 alt="{{ question.author.username }}">
                        {% endif %}
                        Answered by: {{ answer.author.username }}
                    </p>
                    <p> Answer date: {{ answer.creation_date }}</p>

                    <p>Rating: {{ answer.votes_sum }}</p>

                    <!-- Vote block -->
                    {% if user.is_authenticated and user != answer.author %}
                        <form method="post" action={% url 'answer_vote' answer.id %}>
                            {% csrf_token %}
                            <input type="hidden" name="sign" value="-1">
                            {% if answer.vote_status == -1 %}
                                <input class="button" type="submit" value="already -1" aria-pressed="true"/>
                            {% else %}
                                <input class="button" type="submit" value="-1"/>
                            {% endif %}
                        </form>
                        <form method="post" action={% url 'answer_vote' answer.id %}>
                            {% csrf_token %}
                            <input type="hidden" name="sign" value="1">
                            {% if answer.vote_status == 1 %}
                                <input class="button" type="submit" value="already +1" aria-pressed="true"/>
                            {% else %}
                                <input class="button" type="submit" value="+1"/>
                            {% endif %}
                        </form>
                    {% endif %}

                    {% if user == question.author %}
                        <form method="post" action={% url 'answer_mark' answer.id %}>
                            {% csrf_token %}
                            <input class="button" type="submit"
                                   value="{% if answer.correct_answer %}UnMark correct!{% else %}Mark correct!{% endif %}"/>
                        </form>
                    {% else %}
                        {% if answer.correct_answer %}
                            <p>This is correct answer!</p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <hr class="my-4">
        {% endfor %}
    </div>

    {% if user.is_authenticated %}
        <div class="ui divider"></div>
        <h3>Your answer:</h3>
        <form method="post" action={% url 'answer' %}>
            {% csrf_token %}
            <div class="form-group">
                <label for="id_text">Text:</label>
                <textarea name="text" cols="40" rows="10" required="" id="id_text"></textarea>
                <span class="helptext">Provide answer for a question.</span>
            </div>
            <input type="hidden" name="question" value="{{ question.id }}">
            <input class="button" type="submit" value="Send!"/>
        </form>
    {% endif %}
{% endblock %}

07_08_django_hasker/homework/hasker/hasker_qa/templates/hasker_qa/question_info.html
{% load staticfiles %}
<h1>
    <a href="{{ question.get_absolute_url }}">{{ question.title }}</a>
</h1>
<div>
    {% if question.author.avatar %}
        <img src="{{ media_prefix }}{{ question.author.avatar }}" height="30" width="30"
             alt="{{ question.author.username }}">
    {% endif %}
    {{ user.username }}
    asked by: {{ question.author.username }}

</div>
<div>
    {{ question.creation_date }}
</div>

<p>{{ question.text }}</p>
Rating: {{ question.votes_sum }}

07_08_django_hasker/homework/hasker/hasker_qa/templates/hasker_qa/question_tags.html
<!-- Tags -->
<p> Tags:
    {% for tag in question.tags.all %}
        <a href="{% url 'index' %}?q=tag:{{ tag.name }}" class="ui blue label">{{ tag.name }}</a>
    {% endfor %}
</p>